### ISSUE TITLE
allow writing secrets to nested folders

### ISSUE THREAD

**Issue by tam7t** [GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp#125]
Currently the `fileName` parameter in the `SecretProviderClass` parameters cannot have a path separator and is validated by k8s.io/apimachinery/pkg/util/validation.IsConfigMapKey.

A user may want to organize secrets into folder within the mount:

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: app-secrets
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "<RESOURCE_ID>"
        fileName: "api.key"
      - resourceName: "<RESOURCE_ID>"
        fileName: "tls/cert.pem"
      - resourceName: "<RESOURCE_ID>"
        fileName: "tls/key.pem"
      - resourceName: "<RESOURCE_ID>"
        fileName: "foo/bar/baz.txt"
```

Now that all file writes are handled by the driver (#98) and the driver itself uses the same AtomicWriter as other K8s secrets this should be possible without re-introducing [CVE-2020-8567](https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/384)
