### ISSUE TITLE
How to mount secrets in SecretProviderClass as Env Vars in a Pod

### ISSUE THREAD

**Issue by vidocco** [GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp#157]
### Question

Hi! We're trying to use the gcp provider for secret store to mount some secrets as environment variables in a pod. Checking the example provided in the repo, it only shows how to mount them as volumes.

We've been following [this](https://www.vaultproject.io/docs/platform/k8s/csi/examples) example to try and set them as environment variables but it seems like the "parameters" option changes depending on the provider: is there a way of achieving this with the `gcp` provider currently?

**Comment by tam7t** [comment]
https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/issues/37#issuecomment-678833504 has an example that should work.

The `parameters` fields of the `SecretProviderClass` are going to be unique to each individual provider but the part that controls secret syncing to k8s is common among all providers:

```
...
  secretObjects:
  - secretName: foosecret
    type: Opaque
    data: 
    - objectName: good1.txt
      key: pwd
...
```

For this `objectName` must match the `fileName` (or `path`) GCP parameter.

This would create a K8s secret named `foosecret` with a `key` of `pwd` where the `value` is the contents of the `good1.txt` file. From there you can reference the k8s secret for envvars as you would any other k8s secret.

**Comment by vidocco** [comment]
Thanks, that helped! I think an example of how to do this and some documentation would really help (also, maybe the key `fileName` makes things a bit more confusing than they should be but I understand changing it now wouldn't be ideal).

**Comment by idanya** [comment]
Hi,
I'm experiencing an issue trying to sync a GCP secret as a k8s one.
Using the same method without the mapping to a k8s object works well and I can mount secrets as files on the pod's filesystem. 
Trying to create the secret object so I can use the value as ENV (my understanding is that I have to do this kind of mapping in order for the value to be available as ENV) doesn't work. The secret is not being created and no visible errors in the driver pods. 

Installed via Helm with sync enabled and verified the `secretprovidersyncing-role` object present and bound to the driver service account.

Secret:

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: <secret-name>
  namespace: <namespace>
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/.../secrets/<secret-name-in-secret-manager>/versions/latest"
        fileName: "secret.data"
  secretObjects:
    - secretName: <k8s-secret-name>
      type: Opaque
      data: 
      - objectName: secret.data
        key: <key in k8s object>
```


Pod:
```yaml
spec:
  - name: SECRET
      valueFrom:
        secretKeyRef:
          name: <k8s-secret-name>
          key: <key in k8s object>
```
