### ISSUE TITLE
Retrieve list of secrets with only one ResourceName

### ISSUE THREAD

**Issue by safeops-marboleda** [GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp#181]
### TL;DR
Get list of secrets with a wildcard

### Design

**Proposal**
Is it possible to get a list of secrets all together without having to reference every resourceName?
We have a considerable amount of secrets, and it would be easier to do something like:
```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: app-secrets
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/$PROJECT_ID/secrets/*/versions/latest"
        path: "*.txt"
```

**Alternatives considered**
The alternative would be to have a hundreds of lines in the SecretProviderClass, which difficult to maintain.
