### ISSUE TITLE
Does the secrets-store-csi-driver-provider-gcp support request through proxy

### ISSUE THREAD

**Issue by zeusng-fast** [GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp#185]
### Question
Does this driver support traffic through proxy?

We install the driver on our local RKE2 (v2.6.7) environment, which is behind company firewall. Traffic to the Internet goes through a proxy server. We modify the deployment file with the following.

```
...
    spec:
      serviceAccountName: secrets-store-csi-driver-provider-gcp
      containers:
        - name: provider
          image: us-docker.pkg.dev/secretmanager-csi/secrets-store-csi-driver-provider-gcp/plugin@sha256:f7fd197984e95f777557ba9f6daef6c578f49bcddd1080fba0fe8f2c19fffd84
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 50m
              memory: 100Mi
          env:
            - name: TARGET_DIR
              value: "/etc/kubernetes/secrets-store-csi-providers"
            - name: http_proxy
              value: "http://my.proxy.ip:port"
            - name: https_proxy
              value: "http://my.proxy.ip:port"
...
```
From the log file, we see:
```
{"ts":1664342062824.4075,"caller":"infra/grpc.go:35","msg":"request","v":3,"method":"/v1alpha1.CSIDriverProvider/Mount","deadline":"1m59.978652856s"}
{"ts":1664342062826.2651,"caller":"config/config.go:153","msg":"parsed auth","v":3,"auth":"nodePublishSecretRef","pod":{"name":"ns28","namespace":"dm"}}
{"ts":1664342062826.344,"caller":"config/config.go:166","msg":"attributes: REDACTED (envvar DEBUG=true to see values)","v":5,"pod":{"name":"ns28","namespace":"dm"}}
{"ts":1664342062826.5479,"caller":"config/config.go:167","msg":"secrets: REDACTED (envvar DEBUG=true to see values)","v":5,"pod":{"name":"ns28","namespace":"dm"}}
{"ts":1664342062826.607,"caller":"config/config.go:169","msg":"filePermission: -rw-r--r--","v":5,"pod":{"name":"ns28","namespace":"dm"}}
{"ts":1664342062826.6294,"caller":"config/config.go:170","msg":"targetPath: /var/lib/kubelet/pods/8f1a762f-b770-40b4-87a6-f9a707ce4e91/volumes/kubernetes.io~csi/mysecret/mount","v":5,"pod":{"name":"ns28","namespace":"dm"}}
{"ts":1664342100186.24,"caller":"infra/grpc.go:35","msg":"request","v":3,"method":"/v1alpha1.CSIDriverProvider/Mount","deadline":"1m59.906631359s"}
{"ts":1664342100186.8525,"caller":"config/config.go:153","msg":"parsed auth","v":3,"auth":"nodePublishSecretRef","pod":{"name":"nf01","namespace":"dm"}}
{"ts":1664342100187.0461,"caller":"config/config.go:166","msg":"attributes: REDACTED (envvar DEBUG=true to see values)","v":5,"pod":{"name":"nf01","namespace":"dm"}}
{"ts":1664342100187.3337,"caller":"config/config.go:167","msg":"secrets: REDACTED (envvar DEBUG=true to see values)","v":5,"pod":{"name":"nf01","namespace":"dm"}}
{"ts":1664342100187.6572,"caller":"config/config.go:169","msg":"filePermission: -rw-r--r--","v":5,"pod":{"name":"nf01","namespace":"dm"}}
{"ts":1664342100188.2786,"caller":"config/config.go:170","msg":"targetPath: /var/lib/kubelet/pods/9a3e6769-17b2-4842-ac73-2cc6d4ff3a43/volumes/kubernetes.io~csi/mysecret/mount","v":5,"pod":{"name":"nf01","namespace":"dm"}}
{"ts":1664342130586.7507,"caller":"infra/grpc.go:40","msg":"response","v":2,"method":"/v1alpha1.CSIDriverProvider/Mount","deadline":"1m59.966740735s","duration":"1m59.965678871s","status.code":"Internal","status.message":"context canceled"}
{"ts":1664342182803.5273,"caller":"infra/grpc.go:40","msg":"response","v":2,"method":"/v1alpha1.CSIDriverProvider/Mount","deadline":"1m59.978652856s","duration":"1m59.978831432s","status.code":"Internal","status.message":"context canceled"}
```
