### ISSUE TITLE
way to combine synced secrets + static values in single k8s secret?

### ISSUE THREAD

**Issue by parkedwards** [GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp#247]
### Question

While using `SecretProviderClass` to manage k8s secrets (in our case, we're syncing down GCP Secret Manager resources to k8s) - I have a need to create 1 k8s secret with multiple keys.  Some keys will reference a GCP Secret Manager value, but some keys need to be static values

Is that possible at all?

Example:

```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-secrets-provider
spec:
  provider: gcp
  secretObjects:
    - secretName: my-k8s-secret 
      type: Opaque
      data:
        - key: gcp-secret-key
          objectName: gcp-secret-manager-entry.txt
         - key: static-secret-key
          value: "something-static"

```
