### ISSUE TITLE
Create a secret tls on K8S from data of service provider class

### ISSUE THREAD

**Issue by robertsilvatech** [GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp#279]
### Question
I would like know if is possible create a secret with this provider.
In others providers like azure i can see a secret object on Kubernetes, but with a gcp provider i can use it with a volume in my pods.
did anyone manage to do this?

My secret provider class example

```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: csi-secrets
spec:
  provider: gcp
  secretObjects:
    - data:   
      - objectName: "tls.key"
        key: tls.key
      - objectName: "tls.crt"
        key: tls.crt
      type: kubernetes.io/tls
      secretName: $K8S_SECRET_NAME
  parameters:
    secrets: |
      - resourceName: "projects/$PROJECT_ID/secrets/$SECRET_NAME_KEY/versions/latest"
        fileName: "tls.key"               
      - resourceName: "projects/$PROJECT_ID/secrets/$SECRET_NAME_CRT/versions/latest"
        fileName: "tls.crt"      
        

```

**Comment by robertsilvatech** [comment]
I fixed.

In my case I didn't just want to have the secret manager's secret in the pod. I needed to use it in the ingress and for that I needed the secret created.

2 important things
- syncSecret needs to be enabled when install `secrets-store-csi-driver`
- the Pod of the application that will be accessed by the ingress needs to have the volumes mounted.

Follow my configs step by step


## Install secrets-store-csi-driver helm

```
helm repo add secrets-store-csi-driver https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
helm upgrade --install csi-secrets-store secrets-store-csi-driver/secrets-store-csi-driver --set syncSecret.enabled=true \
--namespace kube-system
```

## Install secrets-store-csi-driver-provider-gcp 

```
kubectl apply -f https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/blob/main/deploy/provider-gcp-plugin.yaml
```

## Follow the documentation for create your service account on GCP

> Attention when add-iam-policy-binding svc.id.google[default/myserviceaccount]  
> default is your namespace, if your application run in another namespace do you need change it

## Create a service account

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-secrets
  #namespace: default
  annotations:
    iam.gke.io/gcp-service-account: csi-secrets@$PROJECT_ID.iam.gserviceaccount.com
```

## Create Secret Provider Class

```
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: monitoracao-cert-sync-provider-class
spec:
  provider: gcp
  secretObjects:
    - data:   
      - objectName: "SECRET_NAME_ON_GCP_KEY"
        key: tls.key
      - objectName: "SECRET_NAME_ON_GCP_CRT"
        key: tls.crt
      type: kubernetes.io/tls
      secretName: monitoracao-cert-sync-secret
  parameters:
    secrets: |
      - resourceName: "projects/$PROJECT_ID/secrets/SECRET_NAME_ON_GCP_KEY/versions/latest"
        fileName: "SECRET_NAME_ON_GCP_KEY"               
      - resourceName: "projects/$PROJECT_ID/secrets/SECRET_NAME_ON_GCP_CRT/versions/latest"
        fileName: "SECRET_NAME_ON_GCP_CRT"      
```

## Create your deployment

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: monitoracao-cert-sync-http
  name: monitoracao-cert-sync-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoracao-cert-sync-http
  template:
    metadata:
      labels:
        app: monitoracao-cert-sync-http
    spec:
      serviceAccountName: csi-secrets
      containers:
      - image: hashicorp/http-echo:0.2.3
        imagePullPolicy: IfNotPresent
        args:
        - "-text=<h1>Validacao monitoracao-cert-sync</h1>"
        name: monitoracao-cert-sync-http
        volumeMounts:
          - name: ingress-tls-csi-secret-volume
            mountPath: "/var/secrets"
            readOnly: true
      volumes:
      - name: ingress-tls-csi-secret-volume
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "monitoracao-cert-sync-provider-class"   
```

After create your deployment, you can see a secret object on Kubernetes.  
For debug check log of pod csi-secrets-store-secrets-store-csi-driver.

```
kubectl logs -n kube-system csi-secrets-store-secrets-store-csi-driver-h4xfj |grep monitoracao-cert-sync-http
```

Example Output

```
I0713 13:41:29.872824       1 secretproviderclasspodstatus_controller.go:366] "reconcile complete" spc="staging/monitoracao-cert-sync-provider-class" pod="staging/monitoracao-cert-sync-mount-6667785854-wftsp" spcps="staging/monitoracao-cert-sync-mount-6667785854-wftsp-staging-monitoracao-cert-sync-provider-class"
I0713 13:46:29.873046       1 secretproviderclasspodstatus_controller.go:222] "reconcile started" spcps="staging/monitoracao-cert-sync-mount-6667785854-wftsp-staging-monitoracao-cert-sync-provider-class"
I0713 13:46:29.873375       1 secretproviderclasspodstatus_controller.go:366] "reconcile complete" spc="staging/monitoracao-cert-sync-provider-class" pod="staging/monitoracao-cert-sync-mount-6667785854-wftsp" spcps="staging/monitoracao-cert-sync-mount-6667785854-wftsp-staging-monitoracao-cert-sync-provider-class"
```


## Create your service and ingress

```
kind: Service
apiVersion: v1
metadata:
  name: monitoracao-cert-sync-http-service
spec:
  selector:
    app: monitoracao-cert-sync-http
  ports:
  # Default port used by the image
  - port: 5678
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: monitoracao-cert-sync-http
  name: monitoracao-cert-sync-http-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.allow-http: "true"
spec:
  tls:
    - hosts:
      - monitoracao-cert-sync-http.yourdomain
      secretName: monitoracao-cert-sync-secret
  rules:
  - host: monitoracao-cert-sync-http.yourdomain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: monitoracao-cert-sync-http-service
            port:
              number: 5678
```

Now your certified is working.

For me its working fine
