### ISSUE TITLE
Support Sync with Kubernetes Secrets [optional secrets-store-csi-driver feature]

### ISSUE THREAD

**Issue by kmadel** [GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp#37]
### TL;DR
Add support for syncing to Kubernetes Secrets via `secretObjects`. See https://github.com/kubernetes-sigs/secrets-store-csi-driver#optional-sync-with-kubernetes-secrets

This would allow easier migration of existing pod manifests.

### Design

**Proposal**
Azure example: https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/test/bats/tests/azure/azure_v1alpha1_secretproviderclass_ns.yaml 
Vault example: https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/test/bats/tests/vault/vault_synck8s_v1alpha1_secretproviderclass.yaml 

**Alternatives considered**
No alternative.

**Resources**
Examples:
- Azure example: https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/test/bats/tests/azure/azure_v1alpha1_secretproviderclass_ns.yaml 
- Vault example: https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/master/test/bats/tests/vault/vault_synck8s_v1alpha1_secretproviderclass.yaml 

- [Link to documentation](TODO)

**Comment by tam7t** [comment]
This should be possible currently, although we don't have an example of it yet:

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: app-secrets
spec:
  provider: gcp
  secretObjects:
  - secretName: foosecret
    type: Opaque
    data: 
    - objectName: good1.txt
      key: pwd
  parameters:
    secrets: |
      - resourceName: "projects/$PROJECT_ID/secrets/testsecret/versions/latest"
        fileName: "good1.txt"
```

This will mount the `testsecret` to file `good1.txt` and sync it to a K8S secret called `foosecret`.

**Comment by kmadel** [comment]
The missing piece for me was "fileName" getting mapped to "objectName" but I guess that happens [here](https://github.com/kubernetes-sigs/secrets-store-csi-driver/blob/26c0a5700abf38d9cf8674acc2da29811d250ca0/controllers/secretproviderclasspodstatus_controller.go#L154).
Tested with the following and it worked when a pod was created using the `secretProviderClass`:

```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: cbci-mc-secret-provider
  namespace: cloudbees-core
spec:
  provider: gcp
  secretObjects:
  - secretName: cbci-mc-secret
    type: Opaque
    data: 
    - objectName: token
      key: token
  parameters:
    secrets: |
      - resourceName: "projects/core-workshop/secrets/cbci-workshop-token/versions/latest"
        fileName: "token"
```
